all: A B C D E

A: A.cpp
	clang++ -std=c++17 -O2 -Wall A.cpp -o A

B: B.cpp
	clang++ -std=c++17 -O2 -Wall B.cpp -o B

C: C.cpp
	clang++ -std=c++17 -O2 -Wall C.cpp -o C

D: D.cpp
	clang++ -std=c++17 -O2 -Wall D.cpp -o D

E: E.cpp
	clang++ -std=c++17 -O2 -Wall E.cpp -o E
	